### ISSUE TITLE
A small bug in epsilon Eqn

### ISSUE THREAD

**Issue by graceyangfan** [ffelis/rhokEpsilon#1]
tmp<fvScalarMatrix> epsEqn
    (
        fvm::ddt(rho_, epsilon_)
      + fvm::div(rhoPhi_, epsilon_)
      - fvm::laplacian(rho_*DepsilonEff(), epsilon_)
     ==
        fvm::SuSp(C1_*rho_*G/k_, epsilon_)
      + fvm::SuSp(-((2.0/3.0)*C1_ + C5_)*rho_*divU, epsilon_)
      - fvm::Sp(C2_*rho_*epsilon_/k_, epsilon_)
      + fvm::SuSp(-C1_*io_up2gradp_/k_, epsilon_)
    );
the final source term‘s parameter should be C4_ instead of C1_

    tmp<fvScalarMatrix> epsEqn
    (
        fvm::ddt(rho_, epsilon_)
      + fvm::div(rhoPhi_, epsilon_)
      - fvm::laplacian(rho_*DepsilonEff(), epsilon_)
     ==
        fvm::SuSp(C1_*rho_*G/k_, epsilon_)
      + fvm::SuSp(-((2.0/3.0)*C1_ + C5_)*rho_*divU, epsilon_)
      - fvm::Sp(C2_*rho_*epsilon_/k_, epsilon_)
      + fvm::SuSp(-C4_*io_up2gradp_/k_, epsilon_)
    );

**Comment by ffelis** [comment]
Hi. You are right, there is formally a C4 there from the model. However, we considered it as the same as C1 to match it in the same level as the production term.
